server.port=8085

spring.datasource.url=ENC(2j9KDglPYWsJN6wfIMWrCkEidOMiJB6eUn79XqJ/u0IjryY+gulr5UnFdIrX6JnZcvYFYk1bbEADxuTkPLdIzw==)
spring.datasource.username=ENC(6hTebX6UJDBoaacxM6SEWDuLCqymK48b)
spring.datasource.password=ENC(351oB/HOr1dRfPvxCfMOcLEIgwzXmAZd)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true